use LibraryDB

ALTER TABLE Books
DROP CONSTRAINT FK__Books__GenreID__3C69FB99;

ALTER TABLE Books
ADD CONSTRAINT FK__Books__GenreID__3C69FB99
FOREIGN KEY (GenreID)
REFERENCES Genres(GenreId)
ON DELETE CASCADE;